name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: ebay_manager_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install Dependencies
      run: |
        cd server
        npm ci
        
    - name: Run Tests
      run: |
        cd server
        npm run test
        npm run test:e2e
      env:
        DB_HOST: localhost
        DB_USER: test
        DB_PASSWORD: test
        DB_NAME: ebay_manager_test
        
    - name: Upload Coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and Push API Image
      uses: docker/build-push-action@v4
      with:
        context: ./server
        push: true
        tags: |
          ${{ secrets.DOCKER_REGISTRY }}/ebay-manager-api:${{ github.sha }}
          ${{ secrets.DOCKER_REGISTRY }}/ebay-manager-api:latest
          
    - name: Build and Push Client Image
      uses: docker/build-push-action@v4
      with:
        context: ./client
        push: true
        tags: |
          ${{ secrets.DOCKER_REGISTRY }}/ebay-manager-client:${{ github.sha }}
          ${{ secrets.DOCKER_REGISTRY }}/ebay-manager-client:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install ArgoCD CLI
      run: |
        curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        chmod +x argocd
        sudo mv argocd /usr/local/bin/
        
    - name: Update Kubernetes Manifests
      run: |
        cd k8s
        sed -i "s|image:.*|image: ${{ secrets.DOCKER_REGISTRY }}/ebay-manager-api:${{ github.sha }}|" api-deployment.yaml
        sed -i "s|image:.*|image: ${{ secrets.DOCKER_REGISTRY }}/ebay-manager-client:${{ github.sha }}|" client-deployment.yaml
        
    - name: Commit and Push Updated Manifests
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add k8s/
        git commit -m "Update deployment manifests [skip ci]"
        git push 